"""HTML Report Generation"""
import os
from datetime import datetime
from jinja2 import Template

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<title>GARCH Volatility Report — {{ ticker }}</title>
<style>
body { font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #222; background: #fafafa; }
h1 { color: #1a3e72; border-bottom: 3px solid #1a3e72; padding-bottom: 10px; }
h2 { color: #2c5282; margin-top: 30px; }
table { border-collapse: collapse; width: 100%; margin: 15px 0; background: white; }
th, td { padding: 10px 14px; text-align: left; border: 1px solid #ddd; }
th { background: #1a3e72; color: white; }
tr:nth-child(even) { background: #f5f7fa; }
.metric-box { display: inline-block; padding: 15px 25px; margin: 8px;
              background: white; border-left: 4px solid #1a3e72;
              box-shadow: 0 2px 4px rgba(0,0,0,0.06); border-radius: 4px; }
.metric-label { font-size: 12px; color: #666; text-transform: uppercase; }
.metric-value { font-size: 22px; font-weight: bold; color: #1a3e72; margin-top: 4px; }
.footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ccc;
          color: #888; font-size: 12px; text-align: center; }
</style>
</head>
<body>
<h1>📊 GARCH Volatility Report — {{ ticker }}</h1>
<p><b>Generated:</b> {{ timestamp }} | <b>Period:</b> {{ start_date }} → {{ end_date }} | <b>Best Model:</b> {{ best_model }}</p>

<h2>🎯 Key Metrics</h2>
<div>
{% for key, val in key_metrics.items() %}
<div class="metric-box">
  <div class="metric-label">{{ key }}</div>
  <div class="metric-value">{{ val }}</div>
</div>
{% endfor %}
</div>

<h2>📈 Summary Statistics</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
{% for k, v in summary_stats.items() %}<tr><td>{{ k }}</td><td>{{ v }}</td></tr>{% endfor %}
</table>

<h2>🧪 Statistical Tests</h2>
<table>
<tr><th>Test</th><th>Statistic</th><th>p-value</th><th>Conclusion</th></tr>
<tr><td>ADF (Stationarity)</td><td>{{ adf.adf_stat }}</td><td>{{ adf.p_value }}</td><td>{{ adf.conclusion }}</td></tr>
<tr><td>ARCH-LM (Heteroskedasticity)</td><td>{{ arch.lm_stat }}</td><td>{{ arch.p_value }}</td><td>{{ arch.conclusion }}</td></tr>
</table>

<h2>🏆 Model Comparison</h2>
{{ model_table | safe }}

<h2>⚠️ Risk Metrics</h2>
<table>
<tr><th>Metric</th><th>Value</th></tr>
{% for k, v in risk.items() %}<tr><td>{{ k }}</td><td>{{ v }}</td></tr>{% endfor %}
</table>

<h2>🔮 Volatility Forecast</h2>
{{ forecast_table | safe }}

<div class="footer">Generated by GARCH Volatility Intelligence Platform</div>
</body>
</html>
"""


class ReportGenerator:
    def __init__(self, output_dir: str = "outputs/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate(self, ticker, start_date, end_date, best_model,
                 summary_stats, adf_result, arch_result,
                 comparison_df, risk_report, forecast_df, key_metrics) -> str:
        template = Template(HTML_TEMPLATE)

        def fmt(d):
            return {k: f"{v:.4f}" if isinstance(v, float) else str(v) for k, v in d.items()}

        html = template.render(
            ticker=ticker,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            start_date=start_date,
            end_date=end_date,
            best_model=best_model,
            key_metrics={
                k: f"{v:.4f}" if isinstance(v, float) else v
                for k, v in key_metrics.items()
            },
            summary_stats=fmt(summary_stats),
            adf={
                "adf_stat": f"{adf_result['ADF Statistic']:.4f}",
                "p_value": f"{adf_result['p-value']:.4f}",
                "conclusion": "✅ Stationary" if adf_result["Stationary"] else "❌ Non-stationary",
            },
            arch={
                "lm_stat": f"{arch_result['LM Statistic']:.4f}",
                "p_value": f"{arch_result['LM p-value']:.4f}",
                "conclusion": (
                    "✅ ARCH effects present"
                    if arch_result["ARCH Effects Present"]
                    else "❌ No ARCH"
                ),
            },
            model_table=comparison_df.to_html(index=False, classes="styled"),
            risk=fmt(risk_report),
            forecast_table=forecast_df.round(4).to_html(),
        )

        path = os.path.join(self.output_dir, f"{ticker}_report.html")
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        return path
